### ISSUE TITLE
Script en Bash

### ISSUE THREAD

**Issue by Trocsamas** [Trocsamas/SSII#16]
Creación de un script en bash, que se encargue de la busqueda en anchura de todos los archivos de un directorio y les haga cree un hash a cada uno con el nombre y directorio. Esto se debe de guardar en un documento y posteriormente realizar una comprobación si todos los archivos son iguales.
Para la creación de estos scripts, nos guiaremos mediante https://ss64.com/bash/.

**Comment by IgnacioCVGitHub** [comment]
Añadido fundamento básico de comrpobación de diferencia de entradas de csv. Queda añadir parámetros para generar tasa de modificación y generar ayuda básica por consola

**Comment by IgnacioCVGitHub** [comment]
He creado una primera versión del servicio. hay que seguir una serie de pasos que vienen bastante resumidos en:

- https://askubuntu.com/questions/919054/how-do-i-run-a-single-command-at-startup-using-systemd
- La sección de Creating and installing a service unit de https://linuxconfig.org/how-to-create-systemd-service-unit-in-linux#h5-the-service-section
